### ISSUE TITLE
View records after import

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#25]
In the beta harvester interface, it is possible to delete an imported set. But it isn't possible to view the records of "imported" sets. 

I don't see that this is covered in the harvester specifications. 
But can this be enabled by adding link(s) for each set title on [this page](https://harvester-dev.orbiscascade.org:8443/orbeon/harvester/admin/)? If the user chose to contribute to both DPLA and Primo, ideally he/she would be able to view records transformed and imported for Primo and those for DPLA.

@jallibunn

**Comment by ewg118** [comment]
Finally done. There will now be a link to view the records of the set from the final page of the harvester-interface. It displays 100 records per page as DPLA MAP RDF -> HTML. There is a simple pagination method to allow moving forward and backward through the pages.

**Comment by ewg118** [comment]
By the way, the HTML view could be considered the groundwork for a browse interface. So far, it will either display all records in chronological order (most recent at the top) or accept a URL-encoded OAI-PMH set URL. See http://harvester-dev.orbiscascade.org/results?set=http%3A%2F%2Fcontent.libraries.wsu.edu%2Foai%2Foai.php%3Fverb%3DListRecords%26metadataPrefix%3Doai_dc%26set%3Dmatsura

Eventually, this can be expanded to yield results for faceted searches or keywords.

**Comment by adehner** [comment]
This looks good, and it's very cool that the groundwork is there for a browse interface!

But, we would like the "view records" link to display for each harvested set on this page ( https://harvester-dev.orbiscascade.org:8443/orbeon/harvester/admin/) so members can view their records at any time post-harvest.

**Comment by ewg118** [comment]
Okay, this has been implemented.

**Comment by adehner** [comment]
Please update link text from "view this set as rdf" to...

if set was contributed to DPLA: "view records for DPLA"
if set was contributed to Primo: "view records for Primo"

if set was contributed to both, then both links should appear

**Comment by ewg118** [comment]
Done.

**Comment by adehner** [comment]
This morning I noticed a few weird things when clicking the "view records for Primo" link:

1. When I click "view records for Primo" for the following sets (all from digital commons dams), I see a blank page instead of records:
- All audio stories
- Urban Studies and Planning Dissertations and Theses
- Klipsun Magazine

2. dc:spatial is blank in this set:
Women in Sport at Western

3. dc:rights is a concatenation of standardized and free-text rights statement in this set:
Lee Moorhouse (1850-1926) photographs, 1888-1916

**Comment by ewg118** [comment]
I think I have fixed the issue with 1. With 2., the dcterms:spatial itself is blank, so it's not a rendering problem, but a harvest problem. I checked the XSLT, and empty spatial/coverage values were not being filtered out in cases where there is a semicolon. 3. dc:rights is being split on semicolon again, but I thought we agreed to disable that since rights statements might contain them? I have forgotten now.

**Comment by adehner** [comment]
I'm still seeing instances of empty spatial/coverage for the walc set:
<img width="1228" alt="screen shot 2017-04-28 at 8 55 57 am" src="https://cloud.githubusercontent.com/assets/6174191/25536742/b9ed57ba-2bf0-11e7-80ae-b521226c7d43.png">

**Comment by adehner** [comment]
You are correct about that semicolon in rights! Thanks for reminding us that we don't want to split rights on semicolons. We ask that folks output standardized and free-text rights statements in separate properties, so the moorehouse set is a case for local cleanup.

**Comment by ewg118** [comment]
I restored the dc:rights template so it doesn't split on semicolon.
