### ISSUE TITLE
Add Orbis Cascade Alliance footer to harvester

### ISSUE THREAD

**Issue by adehner** [Orbis-Cascade-Alliance/harvester#46]
Please add the Orbis Cascade Alliance website's footer (https://www.orbiscascade.org/) to the harvester.

@jallibunn

**Comment by ewg118** [comment]
I implemented this in the back end and front end, although the front end will need to have the Orbis Cascade style applied more broadly.

**Comment by adehner** [comment]
Please update the links in the footer.
Looks like they are relative to the harvester right now (eg. Programs points to https://harvester-dev.orbiscascade.org:8443/orbeon/programs instead of https://www.orbiscascade.org/programs)

**Comment by ewg118** [comment]
Fixed

**Comment by adehner** [comment]
Cleared my cache and I'm still seeing relative links. Here's the source from my browser:
<img width="484" alt="screen shot 2017-04-25 at 9 07 26 am" src="https://cloud.githubusercontent.com/assets/6174191/25395739/e4c7799a-2996-11e7-9325-0a2214613613.png">

**Comment by adehner** [comment]
I'm not seeing the update in all pages. The links are all correct, but we would like to see space above the footer on all pages like the screenshot below:

<img width="324" alt="screen shot 2017-04-27 at 10 20 34 am" src="https://cloud.githubusercontent.com/assets/6174191/25495746/33ea4f64-2b33-11e7-9158-744ba1af64dd.png">

**Comment by ewg118** [comment]
I set the top margin of the footer to 30px, which should be applied everywhere
